USE [data_camp];
GO

DECLARE @SnapshotDate DATE = CAST(GETDATE() AS DATE);
DECLARE @DateID INT = CAST(CONVERT(CHAR(8), @SnapshotDate, 112) AS INT);

DELETE FROM OLAP.FACT_LOAN_RISK
WHERE DateID = @DateID;

WITH BASE AS
(
    SELECT
        C.CREDIT_NO,
        C.LOAN_TYPE_ID,
        C.CREDIT_BEGIN_DATE,
        VIS.INSTALLMENT_NO,
        VIS.DUE_FLAG,
        VIS.DAYS_LATE
    FROM DATA.CREDIT C
    JOIN Analysis.VW_INSTALLMENT_STATUS VIS
        ON C.CREDIT_NO = VIS.LOAN_NUMBER
),
LAST_INSTALLMENT AS
(
    SELECT *
    FROM
    (
        SELECT
            CREDIT_NO,
            INSTALLMENT_NO,
            DAYS_LATE,
            ROW_NUMBER() OVER
            (
                PARTITION BY CREDIT_NO
                ORDER BY INSTALLMENT_NO DESC
            ) AS RN
        FROM BASE
        WHERE DUE_FLAG = 'Y'
    ) X
    WHERE RN = 1
),
DPD_AGG AS
(
    SELECT
        CREDIT_NO,
        MAX(CASE WHEN DUE_FLAG = 'Y' THEN DAYS_LATE ELSE 0 END) AS MaximumDPD,
        AVG(CASE WHEN DUE_FLAG = 'Y' THEN DAYS_LATE END) AS AverageDPD
    FROM BASE
    GROUP BY CREDIT_NO
),
OUTSTANDING AS
(
    SELECT
        RS.CREDIT_NO,
        SUM(
            CASE
                WHEN RS.INSTALLMENT_DATE <= @SnapshotDate
                 AND ISNULL(RS.PAID_AMOUNT,0) < RS.INSTALLMENT_SUM
                    THEN RS.INSTALLMENT_SUM - ISNULL(RS.PAID_AMOUNT,0)
                ELSE 0
            END
        ) AS TotalOutstanding
    FROM DATA.REPAYMENT_SCHEDULE RS
    GROUP BY RS.CREDIT_NO
)
INSERT INTO OLAP.FACT_LOAN_RISK
SELECT
    @DateID,
    C.CREDIT_NO,
    DLP.ProductID,
    DLP.ValidFrom,

    ISNULL(LI.DAYS_LATE, 0) AS DPD,
    ISNULL(DA.MaximumDPD, 0),
    ISNULL(DA.AverageDPD, 0),
    ISNULL(O.TotalOutstanding, 0),

    CASE WHEN ISNULL(LI.DAYS_LATE, 0) >= 90 THEN 1 ELSE 0 END,
    CASE WHEN ISNULL(LI.DAYS_LATE, 0) >= 30 THEN 1 ELSE 0 END,

    CASE
        WHEN ISNULL(LI.DAYS_LATE, 0) >= 30
            THEN ISNULL(O.TotalOutstanding, 0)
        ELSE 0
    END

FROM DATA.CREDIT C
LEFT JOIN LAST_INSTALLMENT LI
    ON C.CREDIT_NO = LI.CREDIT_NO
LEFT JOIN DPD_AGG DA
    ON C.CREDIT_NO = DA.CREDIT_NO
LEFT JOIN OUTSTANDING O
    ON C.CREDIT_NO = O.CREDIT_NO
JOIN OLAP.DIM_LOANPRODUCT DLP
    ON DLP.ProductID = C.LOAN_TYPE_ID
   AND C.CREDIT_BEGIN_DATE >= DLP.ValidFrom
   AND (C.CREDIT_BEGIN_DATE <= DLP.ValidTo OR DLP.ValidTo IS NULL);
GO

SELECT *
FROM OLAP.FACT_LOAN_RISK
ORDER BY LoanID;