USE [data_camp];
GO

/*==============================================================*/
/* DROP OLD CONSTRAINTS IF THEY ALREADY EXIST                   */
/*==============================================================*/

IF EXISTS (
   SELECT 1
   FROM sys.objects
   WHERE name = 'DF_CREDIT_STATUS_CODE'
     AND type = 'D'
)
ALTER TABLE DATA.CREDIT
   DROP CONSTRAINT DF_CREDIT_STATUS_CODE;
GO

IF EXISTS (
   SELECT 1
   FROM sys.objects
   WHERE name = 'CK_CREDIT_SUM_POSITIVE'
     AND type = 'C'
)
ALTER TABLE DATA.CREDIT
   DROP CONSTRAINT CK_CREDIT_SUM_POSITIVE;
GO

IF EXISTS (
   SELECT 1
   FROM sys.objects
   WHERE name = 'CK_CREDIT_INTEREST_PRC_POSITIVE'
     AND type = 'C'
)
ALTER TABLE DATA.CREDIT
   DROP CONSTRAINT CK_CREDIT_INTEREST_PRC_POSITIVE;
GO

IF EXISTS (
   SELECT 1
   FROM sys.objects
   WHERE name = 'CK_CREDIT_ALLSUM_POSITIVE'
     AND type = 'C'
)
ALTER TABLE DATA.CREDIT
   DROP CONSTRAINT CK_CREDIT_ALLSUM_POSITIVE;
GO

IF EXISTS (
   SELECT 1
   FROM sys.objects
   WHERE name = 'CK_CREDIT_GPR_POSITIVE'
     AND type = 'C'
)
ALTER TABLE DATA.CREDIT
   DROP CONSTRAINT CK_CREDIT_GPR_POSITIVE;
GO

IF EXISTS (
   SELECT 1
   FROM sys.objects
   WHERE name = 'CK_CREDIT_INSTALLMENT_POSITIVE'
     AND type = 'C'
)
ALTER TABLE DATA.CREDIT
   DROP CONSTRAINT CK_CREDIT_INSTALLMENT_POSITIVE;
GO

IF EXISTS (
   SELECT 1
   FROM sys.objects
   WHERE name = 'CK_CREDIT_INSTALLMENTS_CNT_POSITIVE'
     AND type = 'C'
)
ALTER TABLE DATA.CREDIT
   DROP CONSTRAINT CK_CREDIT_INSTALLMENTS_CNT_POSITIVE;
GO

IF EXISTS (
   SELECT 1
   FROM sys.objects
   WHERE name = 'CK_CREDIT_ENDDATE_GT_BEGINDATE'
     AND type = 'C'
)
ALTER TABLE DATA.CREDIT
   DROP CONSTRAINT CK_CREDIT_ENDDATE_GT_BEGINDATE;
GO

IF EXISTS (
   SELECT 1
   FROM sys.objects
   WHERE name = 'CK_CREDIT_FIRST_MATURITY_PLUS_30'
     AND type = 'C'
)
ALTER TABLE DATA.CREDIT
   DROP CONSTRAINT CK_CREDIT_FIRST_MATURITY_PLUS_30;
GO


/*==============================================================*/
/* DEFAULT STATUS = REGISTERED                                  */
/*==============================================================*/
ALTER TABLE DATA.CREDIT
ADD CONSTRAINT DF_CREDIT_STATUS_CODE
DEFAULT ('R') FOR STATUS_CODE;
GO


/*==============================================================*/
/* POSITIVE VALUE CHECKS                                        */
/*==============================================================*/
ALTER TABLE DATA.CREDIT
ADD CONSTRAINT CK_CREDIT_SUM_POSITIVE
CHECK (CREDIT_SUM > 0);
GO

ALTER TABLE DATA.CREDIT
ADD CONSTRAINT CK_CREDIT_INTEREST_PRC_POSITIVE
CHECK (CREDIT_INTEREST_PRC > 0);
GO

ALTER TABLE DATA.CREDIT
ADD CONSTRAINT CK_CREDIT_ALLSUM_POSITIVE
CHECK (CREDIT_ALLSUM > 0);
GO

ALTER TABLE DATA.CREDIT
ADD CONSTRAINT CK_CREDIT_GPR_POSITIVE
CHECK (CREDIT_GPR > 0);
GO

ALTER TABLE DATA.CREDIT
ADD CONSTRAINT CK_CREDIT_INSTALLMENT_POSITIVE
CHECK (CREDIT_INSTALLMENT > 0);
GO

ALTER TABLE DATA.CREDIT
ADD CONSTRAINT CK_CREDIT_INSTALLMENTS_CNT_POSITIVE
CHECK (CREDIT_ISNTALLMENTS_CNT > 0);
GO


/*==============================================================*/
/* DATE LOGIC CHECKS                                            */
/*==============================================================*/
ALTER TABLE DATA.CREDIT
ADD CONSTRAINT CK_CREDIT_ENDDATE_GT_BEGINDATE
CHECK (CREDIT_END_DATE > CREDIT_BEGIN_DATE);
GO

ALTER TABLE DATA.CREDIT
ADD CONSTRAINT CK_CREDIT_FIRST_MATURITY_PLUS_30
CHECK (CREDIT_FIRST_MATURITY = DATEADD(DAY, 30, CREDIT_BEGIN_DATE));
GO