USE [data_camp];
GO

SET NOCOUNT ON;
GO

DECLARE
    @EMP_1 INT,
    @EMP_2 INT,
    @EMP_3 INT,
    @EMP_4 INT,
    @EMP_5 INT,
    @COMP_ACC_1 INT,
    @COMP_ACC_2 INT,
    @CL_ACC_2 INT,
    @CL_ACC_5 INT,
    @CL_ACC_9 INT,
    @CL_ACC_11 INT,
    @CL_ACC_12 INT,
    @CLIENT_11 INT,
    @CLIENT_12 INT,
    @CR11 NUMERIC(18,0),
    @CR12 NUMERIC(18,0),
    @PAY1 INT,
    @PAY2 INT,
    @PAY3 INT,
    @PAY4 INT,
    @PAY5 INT,
    @PAY6 INT;

/*==============================================================*/
/* 1. EMPLOYEE - add 5 if missing / enough for assignment       */
/*==============================================================*/
IF NOT EXISTS (SELECT 1 FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP001')
BEGIN
    INSERT INTO DATA.EMPLOYEE
    (EMPLOYEE_NAME, EMPLOYEE_SURNAME, EMPLOYEE_LASTNAME, SENIORITY_CODE, COMPANY_IDENTIFIER, EMAIL)
    VALUES ('Иван', 'Петров', 'Георгиев', 'S', 'EMP001', 'ivan.georgiev@creditcompany.bg');
END

IF NOT EXISTS (SELECT 1 FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP002')
BEGIN
    INSERT INTO DATA.EMPLOYEE
    (EMPLOYEE_NAME, EMPLOYEE_SURNAME, EMPLOYEE_LASTNAME, SENIORITY_CODE, COMPANY_IDENTIFIER, EMAIL)
    VALUES ('Мария', 'Николова', 'Иванова', 'M', 'EMP002', 'maria.ivanova@creditcompany.bg');
END

IF NOT EXISTS (SELECT 1 FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP003')
BEGIN
    INSERT INTO DATA.EMPLOYEE
    (EMPLOYEE_NAME, EMPLOYEE_SURNAME, EMPLOYEE_LASTNAME, SENIORITY_CODE, COMPANY_IDENTIFIER, EMAIL)
    VALUES ('Георги', 'Димитров', 'Стоянов', 'J', 'EMP003', 'georgi.stoyanov@creditcompany.bg');
END

IF NOT EXISTS (SELECT 1 FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP004')
BEGIN
    INSERT INTO DATA.EMPLOYEE
    (EMPLOYEE_NAME, EMPLOYEE_SURNAME, EMPLOYEE_LASTNAME, SENIORITY_CODE, COMPANY_IDENTIFIER, EMAIL)
    VALUES ('Петър', 'Иванов', 'Николов', 'S', 'EMP004', 'petar.nikolov@creditcompany.bg');
END

IF NOT EXISTS (SELECT 1 FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP005')
BEGIN
    INSERT INTO DATA.EMPLOYEE
    (EMPLOYEE_NAME, EMPLOYEE_SURNAME, EMPLOYEE_LASTNAME, SENIORITY_CODE, COMPANY_IDENTIFIER, EMAIL)
    VALUES ('Нели', 'Георгиева', 'Петрова', 'M', 'EMP005', 'neli.petrova@creditcompany.bg');
END

SELECT @EMP_1 = EMPLOYEE_ID FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP001';
SELECT @EMP_2 = EMPLOYEE_ID FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP002';
SELECT @EMP_3 = EMPLOYEE_ID FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP003';
SELECT @EMP_4 = EMPLOYEE_ID FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP004';
SELECT @EMP_5 = EMPLOYEE_ID FROM DATA.EMPLOYEE WHERE COMPANY_IDENTIFIER = 'EMP005';

/*==============================================================*/
/* 2. REPAIR EXISTING CREDITS: assign employees if missing      */
/*==============================================================*/
UPDATE DATA.CREDIT
SET EMPLOYEE_ID =
    CASE
        WHEN CREDIT_NO % 5 = 1 THEN @EMP_1
        WHEN CREDIT_NO % 5 = 2 THEN @EMP_2
        WHEN CREDIT_NO % 5 = 3 THEN @EMP_3
        WHEN CREDIT_NO % 5 = 4 THEN @EMP_4
        ELSE @EMP_5
    END
WHERE EMPLOYEE_ID IS NULL;

/*==============================================================*/
/* 3. REPAIR EXISTING SCHEDULE STATUSES                         */
/*==============================================================*/
UPDATE DATA.REPAYMENT_SCHEDULE
SET ISTATUS_CODE =
    CASE
        WHEN CREDIT_NO = 2 AND INSTALLMENT_NO IN (1,2) THEN 'P'
        WHEN CREDIT_NO = 2 AND INSTALLMENT_NO IN (3,4) THEN 'D'
        WHEN CREDIT_NO = 5 THEN 'P'
        WHEN CREDIT_NO = 9 AND INSTALLMENT_NO IN (1,2) THEN 'O'
        WHEN CREDIT_NO = 9 AND INSTALLMENT_NO IN (3,4) THEN 'D'
        WHEN CREDIT_NO = 10 THEN 'D'
        ELSE COALESCE(ISTATUS_CODE, 'D')
    END
WHERE ISTATUS_CODE IS NULL
   OR CREDIT_NO IN (2,5,9,10);

/*==============================================================*/
/* 4. COMPANY BANK ACCOUNTS - 2 ROWS                            */
/*==============================================================*/
IF NOT EXISTS (SELECT 1 FROM DATA.COMPANY_BANK_ACCOUNT WHERE IBAN = 'BG80BNBG96611020345678')
BEGIN
    INSERT INTO DATA.COMPANY_BANK_ACCOUNT (IBAN, BIC, BANK_NAME, ACCOUNT_ACTIVE)
    VALUES ('BG80BNBG96611020345678', 'BNBGBGSD', 'Bulgarian National Bank', 'Y');
END

IF NOT EXISTS (SELECT 1 FROM DATA.COMPANY_BANK_ACCOUNT WHERE IBAN = 'BG12UNCR70001520345678')
BEGIN
    INSERT INTO DATA.COMPANY_BANK_ACCOUNT (IBAN, BIC, BANK_NAME, ACCOUNT_ACTIVE)
    VALUES ('BG12UNCR70001520345678', 'UNCRBGSF', 'UniCredit Bulbank', 'Y');
END

SELECT @COMP_ACC_1 = COMPANY_BANK_ACCOUNT_ID
FROM DATA.COMPANY_BANK_ACCOUNT
WHERE IBAN = 'BG80BNBG96611020345678';

SELECT @COMP_ACC_2 = COMPANY_BANK_ACCOUNT_ID
FROM DATA.COMPANY_BANK_ACCOUNT
WHERE IBAN = 'BG12UNCR70001520345678';

/*==============================================================*/
/* 5. CLIENT BANK ACCOUNTS FOR PAYING EXISTING CLIENTS          */
/*    Client 2 -> Credit 2 Active                               */
/*    Client 5 -> Credit 5 Closed                               */
/*    Client 9 -> Credit 9 Overdue                              */
/*==============================================================*/
IF NOT EXISTS (SELECT 1 FROM DATA.CLIENT_BANK_ACCOUNT WHERE CLIENT_ID = 2)
BEGIN
    INSERT INTO DATA.CLIENT_BANK_ACCOUNT
    (CLIENT_ID, IBAN, BIC, ACCOUNT_HOLDER_NAME, ACCOUNT_ACTIVE)
    VALUES
    (2, 'BG18RZBB91551020345002', 'RZBBBGSF', 'Мария Димитрова Илиева', 'Y');
END

IF NOT EXISTS (SELECT 1 FROM DATA.CLIENT_BANK_ACCOUNT WHERE CLIENT_ID = 5)
BEGIN
    INSERT INTO DATA.CLIENT_BANK_ACCOUNT
    (CLIENT_ID, IBAN, BIC, ACCOUNT_HOLDER_NAME, ACCOUNT_ACTIVE)
    VALUES
    (5, 'BG33BPBI79401020345005', 'BPBIBGSF', 'Георги Маринов Александров', 'Y');
END

IF NOT EXISTS (SELECT 1 FROM DATA.CLIENT_BANK_ACCOUNT WHERE CLIENT_ID = 9)
BEGIN
    INSERT INTO DATA.CLIENT_BANK_ACCOUNT
    (CLIENT_ID, IBAN, BIC, ACCOUNT_HOLDER_NAME, ACCOUNT_ACTIVE)
    VALUES
    (9, 'BG44STSA93000020345009', 'STSABGSF', 'Пламен Дончев Симеонов', 'Y');
END

SELECT @CL_ACC_2 = CLIENT_BANK_ACCOUNT_ID FROM DATA.CLIENT_BANK_ACCOUNT WHERE CLIENT_ID = 2;
SELECT @CL_ACC_5 = CLIENT_BANK_ACCOUNT_ID FROM DATA.CLIENT_BANK_ACCOUNT WHERE CLIENT_ID = 5;
SELECT @CL_ACC_9 = CLIENT_BANK_ACCOUNT_ID FROM DATA.CLIENT_BANK_ACCOUNT WHERE CLIENT_ID = 9;

/*==============================================================*/
/* 6. PAYMENTS FOR EXISTING CREDITS                             */
/*    Credit 2 Active: first 2 installments paid                */
/*    Credit 5 Closed: all 4 installments paid                  */
/*    Credit 9 Overdue: partial insufficient payment            */
/*==============================================================*/

/* Credit 2 */
INSERT INTO DATA.PAYMENT
(
    CREDIT_NO, CLIENT_BANK_ACCOUNT_ID, COMPANY_BANK_ACCOUNT_ID,
    PAYMENT_AMOUNT, PAYMENT_EXECUTED_AT, PAYMENT_VALUE_DATE,
    PAYMENT_REFERENCE, PAYMENT_REASON, PAYMENT_DETAILS, BANK_TRANSACTION_ID
)
VALUES
(2, @CL_ACC_2, @COMP_ACC_1, 3100.00, '2025-10-25T09:10:00', '2025-10-25',
 'PMT-CR2-001', 'Installments 1 and 2', 'Payment covering first two installments', 'BTX-CR2-001');
SET @PAY1 = SCOPE_IDENTITY();

INSERT INTO DATA.PAYMENT_ALLOCATION (PAYMENT_ID, CREDIT_NO, INSTALLMENT_NO, ALLOCATED_AMOUNT)
VALUES
(@PAY1, 2, 1, 1550.00),
(@PAY1, 2, 2, 1550.00);

/* Credit 5 */
INSERT INTO DATA.PAYMENT
(
    CREDIT_NO, CLIENT_BANK_ACCOUNT_ID, COMPANY_BANK_ACCOUNT_ID,
    PAYMENT_AMOUNT, PAYMENT_EXECUTED_AT, PAYMENT_VALUE_DATE,
    PAYMENT_REFERENCE, PAYMENT_REASON, PAYMENT_DETAILS, BANK_TRANSACTION_ID
)
VALUES
(5, @CL_ACC_5, @COMP_ACC_2, 25500.00, '2025-01-25T10:30:00', '2025-01-25',
 'PMT-CR5-001', 'Installments 1 and 2', 'First half of closed mortgage credit', 'BTX-CR5-001');
SET @PAY2 = SCOPE_IDENTITY();

INSERT INTO DATA.PAYMENT_ALLOCATION (PAYMENT_ID, CREDIT_NO, INSTALLMENT_NO, ALLOCATED_AMOUNT)
VALUES
(@PAY2, 5, 1, 12750.00),
(@PAY2, 5, 2, 12750.00);

INSERT INTO DATA.PAYMENT
(
    CREDIT_NO, CLIENT_BANK_ACCOUNT_ID, COMPANY_BANK_ACCOUNT_ID,
    PAYMENT_AMOUNT, PAYMENT_EXECUTED_AT, PAYMENT_VALUE_DATE,
    PAYMENT_REFERENCE, PAYMENT_REASON, PAYMENT_DETAILS, BANK_TRANSACTION_ID
)
VALUES
(5, @CL_ACC_5, @COMP_ACC_2, 25500.00, '2025-03-25T10:45:00', '2025-03-25',
 'PMT-CR5-002', 'Installments 3 and 4', 'Second half of closed mortgage credit', 'BTX-CR5-002');
SET @PAY3 = SCOPE_IDENTITY();

INSERT INTO DATA.PAYMENT_ALLOCATION (PAYMENT_ID, CREDIT_NO, INSTALLMENT_NO, ALLOCATED_AMOUNT)
VALUES
(@PAY3, 5, 3, 12750.00),
(@PAY3, 5, 4, 12750.00);

/* Credit 9 */
INSERT INTO DATA.PAYMENT
(
    CREDIT_NO, CLIENT_BANK_ACCOUNT_ID, COMPANY_BANK_ACCOUNT_ID,
    PAYMENT_AMOUNT, PAYMENT_EXECUTED_AT, PAYMENT_VALUE_DATE,
    PAYMENT_REFERENCE, PAYMENT_REASON, PAYMENT_DETAILS, BANK_TRANSACTION_ID
)
VALUES
(9, @CL_ACC_9, @COMP_ACC_1, 3000.00, '2025-08-28T14:00:00', '2025-08-28',
 'PMT-CR9-001', 'Partial payment', 'Insufficient payment, credit remains overdue', 'BTX-CR9-001');
SET @PAY4 = SCOPE_IDENTITY();

INSERT INTO DATA.PAYMENT_ALLOCATION (PAYMENT_ID, CREDIT_NO, INSTALLMENT_NO, ALLOCATED_AMOUNT)
VALUES
(@PAY4, 9, 1, 3000.00);

/*==============================================================*/
/* 7. 2 NEW CLIENTS                                             */
/*==============================================================*/
INSERT INTO DATA.CLIENT
(
    CLIENT_NAME, CLIENT_SURNAME, CLIENT_LASTNAME, CLIENT_EGN, CLIENT_GENDER,
    CLIENT_BIRTHDATE, CLIENT_IDCARD_NO, CLIENT_IDCARD_ISSUED, CLIENT_IDCARD_VALIDTO,
    CLIENT_IDCARD_ISSUER, EDU_CODE, CLIENT_INCOME, MSTATUS_CODE
)
VALUES
('Калин', 'Стоянов', 'Марков', '8802145678', 'M',
 '1988-02-14', '8012234455', '2021-03-10', '2031-03-10',
 'МВР Варна', 'H', 3400.00, 'M');
SET @CLIENT_11 = SCOPE_IDENTITY();

INSERT INTO DATA.CLIENT
(
    CLIENT_NAME, CLIENT_SURNAME, CLIENT_LASTNAME, CLIENT_EGN, CLIENT_GENDER,
    CLIENT_BIRTHDATE, CLIENT_IDCARD_NO, CLIENT_IDCARD_ISSUED, CLIENT_IDCARD_VALIDTO,
    CLIENT_IDCARD_ISSUER, EDU_CODE, CLIENT_INCOME, MSTATUS_CODE
)
VALUES
('Биляна', 'Тодорова', 'Кирилова', '9409076789', 'F',
 '1994-09-07', '8113345566', '2022-05-18', '2032-05-18',
 'МВР Варна', 'H', 2900.00, 'S');
SET @CLIENT_12 = SCOPE_IDENTITY();

/*==============================================================*/
/* 8. 2 NEW CLIENT ADDRESSES                                    */
/*==============================================================*/
INSERT INTO DATA.CLIENT_ADDRESS
(CLIENT_ID, ADDRESS_PCODE, ADDRESS_TYPE, ADDRESS_TOWN, ADDRESS_TEXT)
VALUES
(@CLIENT_11, '9000', 'P', 'Варна', 'район Приморски, ул. Ген. Колев 18');

INSERT INTO DATA.CLIENT_ADDRESS
(CLIENT_ID, ADDRESS_PCODE, ADDRESS_TYPE, ADDRESS_TOWN, ADDRESS_TEXT)
VALUES
(@CLIENT_12, '9023', 'C', 'Варна', 'кв. Владислав Варненчик, бл. 214, вх. 2, ап. 11');

/*==============================================================*/
/* 9. NEW CLIENT BANK ACCOUNTS                                  */
/*==============================================================*/
INSERT INTO DATA.CLIENT_BANK_ACCOUNT
(CLIENT_ID, IBAN, BIC, ACCOUNT_HOLDER_NAME, ACCOUNT_ACTIVE)
VALUES
(@CLIENT_11, 'BG18RZBB91551020345601', 'RZBBBGSF', 'Калин Стоянов Марков', 'Y');
SET @CL_ACC_11 = SCOPE_IDENTITY();

INSERT INTO DATA.CLIENT_BANK_ACCOUNT
(CLIENT_ID, IBAN, BIC, ACCOUNT_HOLDER_NAME, ACCOUNT_ACTIVE)
VALUES
(@CLIENT_12, 'BG33BPBI79401020345602', 'BPBIBGSF', 'Биляна Тодорова Кирилова', 'Y');
SET @CL_ACC_12 = SCOPE_IDENTITY();

/*==============================================================*/
/* 10. 2 NEW CREDITS                                            */
/*     Credit 11 Active, partially paid                         */
/*     Credit 12 Closed, fully paid                             */
/*==============================================================*/
INSERT INTO DATA.CREDIT
(
    CLIENT_ID, LOAN_TYPE_ID, CREDIT_SIGNED, CREDIT_BEGIN_DATE, CREDIT_END_DATE,
    CREDIT_SUM, CREDIT_INTEREST_PRC, CREDIT_ALLSUM, CREDIT_GPR, STATUS_CODE,
    CREDIT_FIRST_MATURITY, CREDIT_ISNTALLMENTS_CNT, CREDIT_INSTALLMENT, EMPLOYEE_ID
)
VALUES
(@CLIENT_11, 20, 'Y', '2026-04-01', '2026-08-01',
 4800.00, 7.20, 5040.00, 7.80, 'A',
 DATEADD(DAY, 30, '2026-04-01'), 4, 1260.00, @EMP_4);
SET @CR11 = SCOPE_IDENTITY();

INSERT INTO DATA.CREDIT
(
    CLIENT_ID, LOAN_TYPE_ID, CREDIT_SIGNED, CREDIT_BEGIN_DATE, CREDIT_END_DATE,
    CREDIT_SUM, CREDIT_INTEREST_PRC, CREDIT_ALLSUM, CREDIT_GPR, STATUS_CODE,
    CREDIT_FIRST_MATURITY, CREDIT_ISNTALLMENTS_CNT, CREDIT_INSTALLMENT, EMPLOYEE_ID
)
VALUES
(@CLIENT_12, 20, 'Y', '2026-01-15', '2026-05-15',
 3600.00, 6.50, 3840.00, 7.10, 'C',
 DATEADD(DAY, 30, '2026-01-15'), 4, 960.00, @EMP_5);
SET @CR12 = SCOPE_IDENTITY();

/*==============================================================*/
/* 11. NEW REPAYMENT SCHEDULES                                  */
/*==============================================================*/
INSERT INTO DATA.REPAYMENT_SCHEDULE
(CREDIT_NO, INSTALLMENT_NO, INSTALLMENT_DATE, INSTALLMENT_SUM, INSTALLMENT_PRINCIPLE, INSTALLMENT_INTEREST, INSTALLMENT_RESTSUM, ISTATUS_CODE)
VALUES
(@CR11, 1, '2026-05-01', 1260.00, 1200.00, 60.00, 3600.00, 'P'),
(@CR11, 2, '2026-06-01', 1260.00, 1200.00, 60.00, 2400.00, 'X'),
(@CR11, 3, '2026-07-01', 1260.00, 1200.00, 60.00, 1200.00, 'D'),
(@CR11, 4, '2026-08-01', 1260.00, 1200.00, 60.00,    0.00, 'D'),

(@CR12, 1, '2026-02-14',  960.00,  900.00, 60.00, 2700.00, 'P'),
(@CR12, 2, '2026-03-16',  960.00,  900.00, 60.00, 1800.00, 'P'),
(@CR12, 3, '2026-04-15',  960.00,  900.00, 60.00,  900.00, 'P'),
(@CR12, 4, '2026-05-15',  960.00,  900.00, 60.00,    0.00, 'P');

/*==============================================================*/
/* 12. NEW PAYMENTS FOR NEW CREDITS                             */
/*==============================================================*/
INSERT INTO DATA.PAYMENT
(
    CREDIT_NO, CLIENT_BANK_ACCOUNT_ID, COMPANY_BANK_ACCOUNT_ID,
    PAYMENT_AMOUNT, PAYMENT_EXECUTED_AT, PAYMENT_VALUE_DATE,
    PAYMENT_REFERENCE, PAYMENT_REASON, PAYMENT_DETAILS, BANK_TRANSACTION_ID
)
VALUES
(@CR11, @CL_ACC_11, @COMP_ACC_1, 1260.00, '2026-05-01T09:15:00', '2026-05-01',
 'PMT-CR11-001', 'Installment 1', 'Full payment for installment 1', 'BTX-20260501-001');
SET @PAY5 = SCOPE_IDENTITY();

INSERT INTO DATA.PAYMENT
(
    CREDIT_NO, CLIENT_BANK_ACCOUNT_ID, COMPANY_BANK_ACCOUNT_ID,
    PAYMENT_AMOUNT, PAYMENT_EXECUTED_AT, PAYMENT_VALUE_DATE,
    PAYMENT_REFERENCE, PAYMENT_REASON, PAYMENT_DETAILS, BANK_TRANSACTION_ID
)
VALUES
(@CR11, @CL_ACC_11, @COMP_ACC_1, 600.00, '2026-06-03T11:40:00', '2026-06-03',
 'PMT-CR11-002', 'Installment 2', 'Partial payment for installment 2', 'BTX-20260603-002');
SET @PAY6 = SCOPE_IDENTITY();

INSERT INTO DATA.PAYMENT_ALLOCATION
(PAYMENT_ID, CREDIT_NO, INSTALLMENT_NO, ALLOCATED_AMOUNT)
VALUES
(@PAY5, @CR11, 1, 1260.00),
(@PAY6, @CR11, 2,  600.00);

INSERT INTO DATA.PAYMENT
(
    CREDIT_NO, CLIENT_BANK_ACCOUNT_ID, COMPANY_BANK_ACCOUNT_ID,
    PAYMENT_AMOUNT, PAYMENT_EXECUTED_AT, PAYMENT_VALUE_DATE,
    PAYMENT_REFERENCE, PAYMENT_REASON, PAYMENT_DETAILS, BANK_TRANSACTION_ID
)
VALUES
(@CR12, @CL_ACC_12, @COMP_ACC_2, 1920.00, '2026-02-14T10:20:00', '2026-02-14',
 'PMT-CR12-001', 'Installments 1 and 2', 'Payment covering installments 1 and 2', 'BTX-20260214-003');
SET @PAY5 = SCOPE_IDENTITY();

INSERT INTO DATA.PAYMENT
(
    CREDIT_NO, CLIENT_BANK_ACCOUNT_ID, COMPANY_BANK_ACCOUNT_ID,
    PAYMENT_AMOUNT, PAYMENT_EXECUTED_AT, PAYMENT_VALUE_DATE,
    PAYMENT_REFERENCE, PAYMENT_REASON, PAYMENT_DETAILS, BANK_TRANSACTION_ID
)
VALUES
(@CR12, @CL_ACC_12, @COMP_ACC_2, 1920.00, '2026-04-15T15:10:00', '2026-04-15',
 'PMT-CR12-002', 'Installments 3 and 4', 'Payment covering installments 3 and 4', 'BTX-20260415-004');
SET @PAY6 = SCOPE_IDENTITY();

INSERT INTO DATA.PAYMENT_ALLOCATION
(PAYMENT_ID, CREDIT_NO, INSTALLMENT_NO, ALLOCATED_AMOUNT)
VALUES
(@PAY5, @CR12, 1, 960.00),
(@PAY5, @CR12, 2, 960.00),
(@PAY6, @CR12, 3, 960.00),
(@PAY6, @CR12, 4, 960.00);

/*==============================================================*/
/* 13. OPTIONAL VALIDATION                                      */
/*==============================================================*/
PRINT '--- Existing credits with payments ---';
SELECT
    c.CREDIT_NO,
    c.CLIENT_ID,
    c.STATUS_CODE,
    SUM(ISNULL(p.PAYMENT_AMOUNT,0)) AS TOTAL_PAID
FROM DATA.CREDIT c
LEFT JOIN DATA.PAYMENT p
    ON c.CREDIT_NO = p.CREDIT_NO
WHERE c.CREDIT_NO IN (2,5,9,10,@CR11,@CR12)
GROUP BY c.CREDIT_NO, c.CLIENT_ID, c.STATUS_CODE
ORDER BY c.CREDIT_NO;

PRINT '--- Installment statuses for selected credits ---';
SELECT
    CREDIT_NO,
    INSTALLMENT_NO,
    ISTATUS_CODE,
    INSTALLMENT_SUM,
    INSTALLMENT_RESTSUM
FROM DATA.REPAYMENT_SCHEDULE
WHERE CREDIT_NO IN (2,5,9,10,@CR11,@CR12)
ORDER BY CREDIT_NO, INSTALLMENT_NO;
GO