USE [data_camp];
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'Integration')
BEGIN
    EXEC('CREATE SCHEMA Integration');
END
GO

/* Drop child tables first */
IF OBJECT_ID('Integration.PAYMENT_ALLOCATION', 'U') IS NOT NULL DROP TABLE Integration.PAYMENT_ALLOCATION;
IF OBJECT_ID('Integration.PAYMENT', 'U') IS NOT NULL DROP TABLE Integration.PAYMENT;
IF OBJECT_ID('Integration.REPAYMENT_SCHEDULE', 'U') IS NOT NULL DROP TABLE Integration.REPAYMENT_SCHEDULE;
IF OBJECT_ID('Integration.CREDIT', 'U') IS NOT NULL DROP TABLE Integration.CREDIT;
IF OBJECT_ID('Integration.CLIENT_ADDRESS', 'U') IS NOT NULL DROP TABLE Integration.CLIENT_ADDRESS;
IF OBJECT_ID('Integration.CLIENT', 'U') IS NOT NULL DROP TABLE Integration.CLIENT;
GO

CREATE TABLE Integration.CLIENT
(
    CLIENT_ID              INT NULL,
    CLIENT_NAME            VARCHAR(20) NULL,
    CLIENT_SURNAME         VARCHAR(20) NULL,
    CLIENT_LASTNAME        VARCHAR(20) NULL,
    CLIENT_EGN             VARCHAR(10) NULL,
    CLIENT_GENDER          CHAR(1) NULL,
    CLIENT_BIRTHDATE       DATE NULL,
    CLIENT_IDCARD_NO       VARCHAR(10) NULL,
    CLIENT_IDCARD_ISSUED   DATE NULL,
    CLIENT_IDCARD_VALIDTO  DATE NULL,
    CLIENT_IDCARD_ISSUER   VARCHAR(10) NULL,
    EDU_CODE               CHAR(1) NULL,
    CLIENT_INCOME          NUMERIC(10,2) NULL,
    MSTATUS_CODE           CHAR(1) NULL,
    MODIFIED_ON            DATE NULL,
    MODIFIED_BY            VARCHAR(50) NULL,
    SOURCE_SYSTEM          VARCHAR(50) NULL,
    LOAD_DATE              DATETIME NULL
);
GO

CREATE TABLE Integration.CLIENT_ADDRESS
(
    ADDRES_ID INT NULL,
    CLIENT_ID         INT NULL,
    ADDRESS_PCODE     VARCHAR(10) NULL,
    ADDRESS_TYPE      CHAR(1) NULL,
    ADDRESS_TOWN      VARCHAR(50) NULL,
    ADDRESS_TEXT      VARCHAR(200) NULL,
    SOURCE_SYSTEM     VARCHAR(50) NULL,
    LOAD_DATE         DATETIME NULL
);
GO

CREATE TABLE Integration.CREDIT
(
    CREDIT_NO                 NUMERIC(18,0) NULL,
    CLIENT_ID                 INT NULL,
    LOAN_TYPE_ID              INT NULL,
    CREDIT_SIGNED             CHAR(1) NULL,
    CREDIT_BEGIN_DATE         DATE NULL,
    CREDIT_END_DATE           DATE NULL,
    CREDIT_SUM                NUMERIC(10,2) NULL,
    CREDIT_INTEREST_PRC       NUMERIC(5,2) NULL,
    CREDIT_ALLSUM             NUMERIC(10,2) NULL,
    CREDIT_GPR                NUMERIC(5,2) NULL,
    STATUS_CODE               CHAR(1) NULL,
    CREDIT_FIRST_MATURITY     DATE NULL,
    CREDIT_ISNTALLMENTS_CNT   INT NULL,
    CREDIT_INSTALLMENT        NUMERIC(10,2) NULL,
    MODIFIED_ON               DATE NULL,
    MODIFIED_BY               VARCHAR(50) NULL,
    EMPLOYEE_ID               INT NULL,
    CREDIT_PAID_SUM           NUMERIC(10,2) NULL,
    CREDIT_PAYMENT_CNT        INT NULL,
    SOURCE_SYSTEM             VARCHAR(50) NULL,
    LOAD_DATE                 DATETIME NULL
);
GO

CREATE TABLE Integration.REPAYMENT_SCHEDULE
(
    CREDIT_NO                NUMERIC(18,0) NULL,
    INSTALLMENT_NO           INT NULL,
    INSTALLMENT_DATE         DATE NULL,
    INSTALLMENT_SUM          NUMERIC(10,2) NULL,
    INSTALLMENT_PRINCIPLE    NUMERIC(10,2) NULL,
    INSTALLMENT_INTEREST     NUMERIC(10,2) NULL,
    INSTALLMENT_RESTSUM      NUMERIC(10,2) NULL,
    ISTATUS_CODE             CHAR(1) NULL,
    MODIFIED_ON              DATE NULL,
    MODIFIED_BY              VARCHAR(50) NULL,
    PAID_AMOUNT              NUMERIC(10,2) NULL,
    PAID_ON                  DATE NULL,
    SOURCE_SYSTEM            VARCHAR(50) NULL,
    LOAD_DATE                DATETIME NULL
);
GO

CREATE TABLE Integration.PAYMENT
(
    PAYMENT_ID             INT NULL,
    CREDIT_NO              NUMERIC(18,0) NULL,
    PAYMENT_AMOUNT         NUMERIC(10,2) NULL,
    PAYMENT_VALUE_DATE     DATE NULL,
    PAYMENT_EXECUTED_AT    DATETIME NULL,
    PAYMENT_REFERENCE      VARCHAR(50) NULL,
    MODIFIED_ON            DATE NULL,
    MODIFIED_BY            VARCHAR(50) NULL,
    SOURCE_SYSTEM          VARCHAR(50) NULL,
    LOAD_DATE              DATETIME NULL
);
GO

CREATE TABLE Integration.PAYMENT_ALLOCATION
(
    PAYMENT_ID          INT NULL,
    CREDIT_NO           NUMERIC(18,0) NULL,
    INSTALLMENT_NO      INT NULL,
    ALLOCATED_AMOUNT    NUMERIC(10,2) NULL,
    MODIFIED_ON         DATE NULL,
    MODIFIED_BY         VARCHAR(50) NULL,
    SOURCE_SYSTEM       VARCHAR(50) NULL,
    LOAD_DATE           DATETIME NULL
);
GO