INSERT INTO Integration.CLIENT
(
    CLIENT_ID,
    CLIENT_NAME,
    CLIENT_SURNAME,
    CLIENT_LASTNAME,
    CLIENT_EGN,
    CLIENT_GENDER,
    CLIENT_BIRTHDATE,
    CLIENT_IDCARD_NO,
    CLIENT_IDCARD_ISSUED,
    CLIENT_IDCARD_VALIDTO,
    CLIENT_IDCARD_ISSUER,
    EDU_CODE,
    CLIENT_INCOME,
    MSTATUS_CODE,
    SOURCE_SYSTEM,
    LOAD_DATE
)
SELECT
    CAST(CLIENT_ID AS INT),
    CLIENT_NAME,
    CLIENT_SURNAME,
    CLIENT_LASTNAME,
    CLIENT_EGN,
    CLIENT_GENDER,
    CAST(CLIENT_BIRTHDATE AS DATE),
    CLIENT_IDCARD_NO,
    CAST(CLIENT_IDCARD_ISSUED AS DATE),
    CAST(CLIENT_IDCARD_VALIDTO AS DATE),
    CLIENT_IDCARD_ISSUER,
    EDU_CODE,
    CAST(CLIENT_INCOME AS DECIMAL(10,2)),
    MSTATUS_CODE,
    'CSV',
    GETDATE()
FROM Integration.RAW_CUSTOMERS;

GO

INSERT INTO Integration.CREDIT
(
    CREDIT_NO,
    CLIENT_ID,
    LOAN_TYPE_ID,
    CREDIT_SIGNED,
    CREDIT_BEGIN_DATE,
    CREDIT_END_DATE,
    CREDIT_SUM,
    CREDIT_INTEREST_PRC,
    CREDIT_ALLSUM,
    CREDIT_GPR,
    STATUS_CODE,
    CREDIT_FIRST_MATURITY,
    CREDIT_ISNTALLMENTS_CNT,
    CREDIT_INSTALLMENT,
    SOURCE_SYSTEM,
    LOAD_DATE
)
SELECT
    CAST(RC.CREDIT_NO AS INT),
    C.CLIENT_ID,
    CAST(RC.LOAN_TYPE_ID AS INT),
    RC.CREDIT_SIGNED,
    CAST(RC.CREDIT_BEGIN_DATE AS DATE),
    CAST(RC.CREDIT_END_DATE AS DATE),
    CAST(RC.CREDIT_SUM AS DECIMAL(10,2)),
    CAST(RC.CREDIT_INTEREST_PRC AS DECIMAL(5,2)),
    CAST(RC.CREDIT_ALLSUM AS DECIMAL(10,2)),
    CAST(RC.CREDIT_GPR AS DECIMAL(5,2)),
    RC.STATUS_CODE,
    CAST(RC.CREDIT_FIRST_MATURITY AS DATE),
    CAST(RC.CREDIT_ISNTALLMENTS_CNT AS INT),
    CAST(RC.CREDIT_INSTALLMENT AS DECIMAL(10,2)),
    'CSV',
    GETDATE()
FROM Integration.RAW_CREDITS RC
JOIN Integration.CLIENT C
    ON RC.CLIENT_EGN = C.CLIENT_EGN;

GO

INSERT INTO Integration.REPAYMENT_SCHEDULE
(
    CREDIT_NO,
    INSTALLMENT_NO,
    INSTALLMENT_DATE,
    INSTALLMENT_SUM,
    INSTALLMENT_PRINCIPLE,
    INSTALLMENT_INTEREST,
    INSTALLMENT_RESTSUM,
    ISTATUS_CODE,
    PAID_AMOUNT,
    PAID_ON,
    SOURCE_SYSTEM,
    LOAD_DATE
)
SELECT
    CAST(CREDIT_NO AS INT),
    CAST(INSTALLMENT_NO AS INT),
    CAST(INSTALLMENT_DATE AS DATE),
    CAST(INSTALLMENT_SUM AS DECIMAL(10,2)),
    CAST(INSTALLMENT_PRINCIPLE AS DECIMAL(10,2)),
    CAST(INSTALLMENT_INTEREST AS DECIMAL(10,2)),
    CAST(INSTALLMENT_RESTSUM AS DECIMAL(10,2)),
    ISTATUS_CODE,
    CAST(PAID_AMOUNT AS DECIMAL(10,2)),
    CAST(PAID_ON AS DATE),
    'CSV',
    GETDATE()
FROM Integration.RAW_REPAYMENT;
GO



