use data_camp

INSERT INTO [Data].[EDUCATION]  ([EDU_CODE],[EDU_NAME])  VALUES ('P', 'Primary');
INSERT INTO [Data].[EDUCATION]  ([EDU_CODE],[EDU_NAME])  VALUES ('S', 'Secondary');
INSERT INTO [Data].[EDUCATION]  ([EDU_CODE],[EDU_NAME])  VALUES ('H', 'Higher');

INSERT INTO [Data].[MARITAL_STATUS] ([MSTATUS_CODE],[MSTATUS_NAME]) VALUES ('S', 'Single');
INSERT INTO [Data].[MARITAL_STATUS] ([MSTATUS_CODE],[MSTATUS_NAME]) VALUES ('M', 'Married');
INSERT INTO [Data].[MARITAL_STATUS] ([MSTATUS_CODE],[MSTATUS_NAME]) VALUES ('D', 'Divorced');
INSERT INTO [Data].[MARITAL_STATUS] ([MSTATUS_CODE],[MSTATUS_NAME]) VALUES ('W', 'Widow');

INSERT INTO [Data].[STATUS]   ([STATUS_CODE]  ,[STATUS_NAME]) VALUES ('R', 'Registered');
INSERT INTO [Data].[STATUS]   ([STATUS_CODE]  ,[STATUS_NAME]) VALUES ('V', 'Verified');
INSERT INTO [Data].[STATUS]   ([STATUS_CODE]  ,[STATUS_NAME]) VALUES ('I', 'Inspection');
INSERT INTO [Data].[STATUS]   ([STATUS_CODE]  ,[STATUS_NAME]) VALUES ('A', 'Active');
INSERT INTO [Data].[STATUS]   ([STATUS_CODE]  ,[STATUS_NAME]) VALUES ('C', 'Closed');
INSERT INTO [Data].[STATUS]   ([STATUS_CODE]  ,[STATUS_NAME]) VALUES ('O', 'Overdue');

INSERT INTO [Data].[LOAN_TYPE]   ([LOAN_TYPE_ID]  ,[LAON_TYPE_NAME]) VALUES (10, 'Mortgage Loan');
INSERT INTO [Data].[LOAN_TYPE]   ([LOAN_TYPE_ID]  ,[LAON_TYPE_NAME]) VALUES (20, 'Personal Loan');
INSERT INTO [Data].[LOAN_TYPE]   ([LOAN_TYPE_ID]  ,[LAON_TYPE_NAME]) VALUES (30, 'Auto Loan');
INSERT INTO [Data].[LOAN_TYPE]   ([LOAN_TYPE_ID]  ,[LAON_TYPE_NAME]) VALUES (40, 'Student Loan');
INSERT INTO [Data].[LOAN_TYPE]   ([LOAN_TYPE_ID]  ,[LAON_TYPE_NAME]) VALUES (50, 'Business Loan');