USE [data_camp];
GO

/*==============================================================*/
/* DROP VIEW IF EXISTS                                          */
/*==============================================================*/
IF OBJECT_ID('Analysis.VW_LOAN_BALANCE', 'V') IS NOT NULL
    DROP VIEW Analysis.VW_LOAN_BALANCE;
GO

/*==============================================================*/
/* VIEW: LOAN BALANCE                                           */
/*==============================================================*/
CREATE VIEW Analysis.VW_LOAN_BALANCE
AS
WITH DUE_AMOUNTS AS
(
    SELECT
        RS.CREDIT_NO,
        SUM(
            CASE
                WHEN RS.INSTALLMENT_DATE <= CAST(GETDATE() AS DATE)
                    THEN RS.INSTALLMENT_SUM
                ELSE 0
            END
        ) AS TOTAL_DUE_AMOUNT,
        MAX(
            CASE
                WHEN RS.INSTALLMENT_DATE <= CAST(GETDATE() AS DATE)
                    THEN RS.INSTALLMENT_DATE
                ELSE NULL
            END
        ) AS LAST_INSTALLMENT_DUE_DATE
    FROM DATA.REPAYMENT_SCHEDULE RS
    GROUP BY RS.CREDIT_NO
),
PAID_AMOUNTS AS
(
    SELECT
        P.CREDIT_NO,
        SUM(P.PAYMENT_AMOUNT) AS TOTAL_PAID_AMOUNT,
        MAX(ISNULL(P.PAYMENT_VALUE_DATE, CAST(P.PAYMENT_EXECUTED_AT AS DATE))) AS LAST_PAYMENT_DATE
    FROM DATA.PAYMENT P
    GROUP BY P.CREDIT_NO
),
AVG_INSTALLMENT_LATE AS
(
    SELECT
        VIS.LOAN_NUMBER,
        AVG(CAST(VIS.DAYS_LATE AS DECIMAL(10,2))) AS AVG_INSTALLMENT_LATE
    FROM Analysis.VW_INSTALLMENT_STATUS VIS
    WHERE VIS.DUE_FLAG = 'Y'
    GROUP BY VIS.LOAN_NUMBER
)
SELECT
    C.CREDIT_NO AS LOAN_NUMBER,
    C.CREDIT_ALLSUM AS LOAN_AMOUNT,
    ISNULL(DA.TOTAL_DUE_AMOUNT, 0) AS TOTAL_DUE_AMOUNT,
    ISNULL(PA.TOTAL_PAID_AMOUNT, 0) AS TOTAL_PAID_AMOUNT,
    C.CREDIT_ALLSUM - ISNULL(PA.TOTAL_PAID_AMOUNT, 0) AS TOTAL_BALANCE,

    CASE
        WHEN ISNULL(DA.TOTAL_DUE_AMOUNT, 0) - ISNULL(PA.TOTAL_PAID_AMOUNT, 0) < 0 THEN 0
        ELSE ISNULL(DA.TOTAL_DUE_AMOUNT, 0) - ISNULL(PA.TOTAL_PAID_AMOUNT, 0)
    END AS DUE_BALANCE,

    CASE
        WHEN DA.LAST_INSTALLMENT_DUE_DATE IS NULL THEN 0
        WHEN PA.LAST_PAYMENT_DATE IS NULL THEN 0
        WHEN DATEDIFF(DAY, DA.LAST_INSTALLMENT_DUE_DATE, PA.LAST_PAYMENT_DATE) < 0 THEN 0
        ELSE DATEDIFF(DAY, DA.LAST_INSTALLMENT_DUE_DATE, PA.LAST_PAYMENT_DATE)
    END AS LOAN_LATE,

    ISNULL(AIL.AVG_INSTALLMENT_LATE, 0) AS AVG_INSTALLMENT_LATE

FROM DATA.CREDIT C
LEFT JOIN DUE_AMOUNTS DA
    ON C.CREDIT_NO = DA.CREDIT_NO
LEFT JOIN PAID_AMOUNTS PA
    ON C.CREDIT_NO = PA.CREDIT_NO
LEFT JOIN AVG_INSTALLMENT_LATE AIL
    ON C.CREDIT_NO = AIL.LOAN_NUMBER;
GO

-- test
SELECT *
FROM Analysis.VW_LOAN_BALANCE
ORDER BY LOAN_NUMBER;