USE [data_camp];
GO

/*==============================================================*/
/* VALID EGN TEST DATA                                          */
/*==============================================================*/

UPDATE DATA.CLIENT
SET CLIENT_EGN = '0243150000',
    CLIENT_BIRTHDATE = '2002-03-15',
    CLIENT_GENDER = 'M'
WHERE CLIENT_ID = 1;

UPDATE DATA.CLIENT
SET CLIENT_EGN = '0347220012',
    CLIENT_BIRTHDATE = '2003-07-22',
    CLIENT_GENDER = 'F'
WHERE CLIENT_ID = 2;

/* valid EGN, wrong gender on purpose */
UPDATE DATA.CLIENT
SET CLIENT_EGN = '9201110006',
    CLIENT_BIRTHDATE = '1992-01-11',
    CLIENT_GENDER = 'F'
WHERE CLIENT_ID = 3;

/* valid EGN, wrong birthdate on purpose */
UPDATE DATA.CLIENT
SET CLIENT_EGN = '9109080012',
    CLIENT_BIRTHDATE = '1991-09-09',
    CLIENT_GENDER = 'F'
WHERE CLIENT_ID = 4;

UPDATE DATA.CLIENT
SET CLIENT_EGN = '7812010007',
    CLIENT_BIRTHDATE = '1978-12-01',
    CLIENT_GENDER = 'M'
WHERE CLIENT_ID = 5;

UPDATE DATA.CLIENT
SET CLIENT_EGN = '8504300014',
    CLIENT_BIRTHDATE = '1985-04-30',
    CLIENT_GENDER = 'F'
WHERE CLIENT_ID = 6;

UPDATE DATA.CLIENT
SET CLIENT_EGN = '8906170001',
    CLIENT_BIRTHDATE = '1989-06-17',
    CLIENT_GENDER = 'M'
WHERE CLIENT_ID = 7;

UPDATE DATA.CLIENT
SET CLIENT_EGN = '0442030013',
    CLIENT_BIRTHDATE = '2004-02-03',
    CLIENT_GENDER = 'F'
WHERE CLIENT_ID = 8;

UPDATE DATA.CLIENT
SET CLIENT_EGN = '7609120001',
    CLIENT_BIRTHDATE = '1976-09-12',
    CLIENT_GENDER = 'M'
WHERE CLIENT_ID = 9;

UPDATE DATA.CLIENT
SET CLIENT_EGN = '9305260013',
    CLIENT_BIRTHDATE = '1993-05-26',
    CLIENT_GENDER = 'F'
WHERE CLIENT_ID = 10;

/* valid EGN, wrong birthdate and gender on purpose */
UPDATE DATA.CLIENT
SET CLIENT_EGN = '8802140005',
    CLIENT_BIRTHDATE = '1988-02-15',
    CLIENT_GENDER = 'F'
WHERE CLIENT_ID = 11;

UPDATE DATA.CLIENT
SET CLIENT_EGN = '9409070015',
    CLIENT_BIRTHDATE = '1994-09-07',
    CLIENT_GENDER = 'F'
WHERE CLIENT_ID = 12;

/*==============================================================*/
/* INVALID EGN TEST DATA                                        */
/*==============================================================*/

/* invalid checksum */
UPDATE DATA.CLIENT
SET CLIENT_EGN = '6501011111',
    CLIENT_BIRTHDATE = '1965-01-01',
    CLIENT_GENDER = 'M'
WHERE CLIENT_ID = 13;

/* invalid checksum */
UPDATE DATA.CLIENT
SET CLIENT_EGN = '9005052222',
    CLIENT_BIRTHDATE = '1990-05-05',
    CLIENT_GENDER = 'F'
WHERE CLIENT_ID = 14;
GO

-- test

SELECT
    CLIENT_ID,
    CLIENT_NAME,
    CLIENT_SURNAME,
    CLIENT_LASTNAME,
    CLIENT_EGN,
    CLIENT_BIRTHDATE,
    CLIENT_GENDER,
    DATA.FN_EGN_IS_VALID(CLIENT_EGN) AS EGN_IS_VALID,
    DATA.FN_EGN_DECODE_BIRTHDATE(CLIENT_EGN) AS DECODED_BIRTHDATE,
    DATA.FN_EGN_DECODE_GENDER(CLIENT_EGN) AS DECODED_GENDER
FROM DATA.CLIENT
ORDER BY CLIENT_ID;