USE [data_camp];
GO

INSERT INTO OLAP.DIM_CUSTOMER
(
    CustomerID,
    FirstName,
    LastName,
    Gender,
    BirthDate
)
SELECT
    C.CLIENT_ID,
    C.CLIENT_NAME,
    C.CLIENT_LASTNAME,
    C.CLIENT_GENDER,
    C.CLIENT_BIRTHDATE
FROM DATA.CLIENT C
WHERE NOT EXISTS
(
    SELECT 1
    FROM OLAP.DIM_CUSTOMER D
    WHERE D.CustomerID = C.CLIENT_ID
);
GO

SELECT COUNT(*) AS DIM_CUSTOMER_CNT
FROM OLAP.DIM_CUSTOMER;